# Deploy on EC2
- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY }}

    script: |

      # Stop old container
      sudo docker stop portfolio || true

      # Remove old container
      sudo docker rm portfolio || true

      # Pull latest image
      sudo docker pull ehsantechn/portfolio:${{ github.run_number }}

      # Run latest image
      sudo docker run -d \
      --name portfolio \
      -p 80:80 \
      ehsantechn/portfolio:${{ github.run_number }}
